declare namespace JAD {
    export interface IProjectOptions {
        name: string;
        animations: ja.IAnimationOptions[];
    }

    export type PropertyType =
        // Web/CSS/angle The angle CSS data type represents angle values. Positive angles represent clockwise angles, ...
        'angle'
        // Web/CSS/basic-shape The basic-shape type can be specified using basic shape functions. When using this syntax to define ...
        | 'basic-shape'
        // Web/CSS/blend-mode The blend-mode type is a collection of keywords describing blend modes.
        | 'blend-mode'
        // Web/CSS/color_value The color CSS data type denotes a color in the sRGB color space. A color can be described in any of ...
        | 'color_value'
        // Web/CSS/custom-ident The custom-ident CSS data value denotes an arbitrary user-defined string used as an identifier. It ...
        | 'custom-ident'
        // Web/CSS/gradient The gradient CSS data type denotes a CSS image made of a progressive transition between two or more ...
        | 'gradient'
        // Web/CSS/image The image CSS data type represents a 2D image. There are two kinds of images in CSS: plain static ...
        | 'image'
        // Web/CSS/integer The integer CSS data type denotes an integer number, positive or negative. There isn't any ...
        | 'integer'
        // Web/CSS/length The length CSS data type denotes distance measurements. It is a number immediately followed by a ...
        | 'length'
        // Web/CSS/number The number CSS data type represents a number, either integer or fractional. Its syntax extends the ...
        | 'number'
        // Web/CSS/percentage The percentage CSS data types represent a percentage value. Many CSS properties can take percentage ...
        | 'percentage'
        // Web/CSS/position_value The position CSS data type denotes a coordinate in a 2D space used to set a location relative to a ...
        | 'position_value'
        // Web/CSS/ratio The ratio CSS data type, used for describing aspect ratios in media queries, denotes the proportion ...
        | 'ratio'
        // Web/CSS/resolution The resolution CSS data types, used in media queries, denotes the density of pixels of an output ...
        | 'resolution'
        // Web/CSS/shape The shape CSS data type denotes the specific form of a region. This region is used to define on ...
        | 'shape'
        // Web/CSS/shape-box Shapes can be specified for shape-outside with a shape-box type, which is a reference to edges in ...
        | 'shape-box'
        // Web/CSS/string The string CSS data type represents a string. It is formed by a Unicode characters delimited by ...
        | 'string'
        // Web/CSS/time The time CSS data type denotes time dimensions expressed in seconds or milliseconds. They consists ...
        | 'time'
        // Web/CSS/timing-function The timing-function CSS data type denotes a mathematical function that describes how fast ...
        | 'timing-function'
        // Web/CSS/transform-function The transform-function CSS data type denotes a function applied to an element's representation in ...
        | 'transform-function'
        // included for type escaping
        | string;

    export interface IModelDescriptor {
        properties: IPropertyDescriptor[];
        type: Function;
    }

    export interface IPropertyDescriptor {
        name: string;
        restrict?: boolean;
        selections?: string[];
        type: PropertyType;
    }
}